
import com.sun.glass.events.KeyEvent;
import javax.swing.JFrame;

import javax.swing.JOptionPane;


public class fastfood extends javax.swing.JFrame {
 double price_grill =70;
    double price_cheese = 55;
    double price_vege = 45;
    double price_coke = 15;
    double price_lassi = 10;
    double price_limbu = 10;
    double Tax_Rate = 3.5;
    
    double total,  Subtotal , tax, cost;
   
    double[] itemcost = new double[8];
    
    /**
     * Creates new form fastfood
     */
    public fastfood() {
                     initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        taxtext = new javax.swing.JTextField();
        subtext = new javax.swing.JTextField();
        totaltext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        grillcheck = new javax.swing.JCheckBox();
        cheesecheck = new javax.swing.JCheckBox();
        vegecheck = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        grilltext = new javax.swing.JTextField();
        vegetext = new javax.swing.JTextField();
        cheesetext = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        cokecheck = new javax.swing.JCheckBox();
        lassicheck = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        coketext = new javax.swing.JTextField();
        limbutext = new javax.swing.JTextField();
        limbucheck = new javax.swing.JCheckBox();
        lassitext = new javax.swing.JTextField();
        resetbut = new javax.swing.JButton();
        totalbut = new javax.swing.JButton();
        exitbut = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 86, 145));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 238, 172));
        jLabel1.setText("STATION");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fast-food (1).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(244, 209, 96));
        jLabel9.setText("GRILL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(42, 42, 42))
        );

        jPanel2.setBackground(new java.awt.Color(232, 241, 245));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("PAYMENT");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit Card", "Master Card", "Visa Card" }));

        taxtext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        taxtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxtextActionPerformed(evt);
            }
        });

        subtext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtextActionPerformed(evt);
            }
        });

        totaltext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totaltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tax");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Subtotal");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subtext, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(taxtext, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(86, 86, 86)
                        .addComponent(totaltext, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addGap(48, 48, 48)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(subtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totaltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(232, 241, 245));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FOOD ITEMS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("QUANTITY");

        grillcheck.setBackground(new java.awt.Color(248, 243, 212));
        grillcheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        grillcheck.setText("Grill cheese Sandwich");
        grillcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grillcheckActionPerformed(evt);
            }
        });

        cheesecheck.setBackground(new java.awt.Color(248, 243, 212));
        cheesecheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cheesecheck.setText("Cheese Sandwich");
        cheesecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheesecheckActionPerformed(evt);
            }
        });

        vegecheck.setBackground(new java.awt.Color(248, 243, 212));
        vegecheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vegecheck.setText("Vegetable Sandwich");
        vegecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegecheckActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox4.setText("Coke.....250ml");

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox5.setText("Lassi.....250ml");

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox6.setText("Limbu Soda....250ml");

        grilltext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        grilltext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        grilltext.setText("0");
        grilltext.setEnabled(false);
        grilltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grilltextActionPerformed(evt);
            }
        });
        grilltext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                grilltextKeyTyped(evt);
            }
        });

        vegetext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vegetext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vegetext.setText("0");
        vegetext.setEnabled(false);
        vegetext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vegetextKeyTyped(evt);
            }
        });

        cheesetext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cheesetext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cheesetext.setText("0");
        cheesetext.setEnabled(false);
        cheesetext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cheesetextKeyTyped(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        cokecheck.setBackground(new java.awt.Color(248, 243, 212));
        cokecheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cokecheck.setText("Coke.....250ml");
        cokecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokecheckActionPerformed(evt);
            }
        });

        lassicheck.setBackground(new java.awt.Color(248, 243, 212));
        lassicheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lassicheck.setText("Lassi.....250ml");
        lassicheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lassicheckActionPerformed(evt);
            }
        });

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox9.setText("Vegetable Sandwich");

        coketext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        coketext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        coketext.setText("0");
        coketext.setEnabled(false);
        coketext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                coketextKeyTyped(evt);
            }
        });

        limbutext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limbutext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        limbutext.setText("0");
        limbutext.setEnabled(false);
        limbutext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                limbutextKeyTyped(evt);
            }
        });

        limbucheck.setBackground(new java.awt.Color(248, 243, 212));
        limbucheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limbucheck.setText("Limbu Soda...250ml");
        limbucheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limbucheckActionPerformed(evt);
            }
        });

        lassitext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lassitext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lassitext.setText("0");
        lassitext.setEnabled(false);
        lassitext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lassitextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(jTextField4))
                            .addComponent(jCheckBox9)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(grillcheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(grilltext, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cokecheck)
                            .addComponent(lassicheck)
                            .addComponent(cheesecheck)
                            .addComponent(limbucheck)
                            .addComponent(vegecheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vegetext)
                            .addComponent(cheesetext)
                            .addComponent(coketext, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(limbutext)
                            .addComponent(lassitext))))
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grillcheck)
                    .addComponent(grilltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheesetext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheesecheck))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vegetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coketext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cokecheck))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lassitext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lassicheck))))
                    .addComponent(vegecheck))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limbutext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limbucheck))
                .addGap(252, 252, 252)
                .addComponent(jCheckBox9)
                .addGap(37, 37, 37)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(jCheckBox4)
                .addGap(36, 36, 36)
                .addComponent(jCheckBox5)
                .addGap(23, 23, 23)
                .addComponent(jCheckBox6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resetbut.setBackground(new java.awt.Color(222, 131, 77));
        resetbut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resetbut.setText("Reset");
        resetbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbutActionPerformed(evt);
            }
        });

        totalbut.setBackground(new java.awt.Color(255, 253, 222));
        totalbut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalbut.setText("Total");
        totalbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbutActionPerformed(evt);
            }
        });

        exitbut.setBackground(new java.awt.Color(255, 113, 113));
        exitbut.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitbut.setText("Exit");
        exitbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbutMouseClicked(evt);
            }
        });
        exitbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(resetbut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(totalbut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitbut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalbut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetbut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void taxtextActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void subtextActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void totaltextActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void exitbutMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
       
    }                                    

    private void exitbutActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
      JFrame   frame = new JFrame("Exit");
        
        if(JOptionPane.showConfirmDialog(frame, "Confim you want to exit?", "FastFood", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }                                       

    private void resetbutActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        grilltext.setText("0");
        cheesetext.setText("0");
        vegetext.setText("0");
        coketext.setText("0");
        lassitext.setText("0");
        limbutext.setText("0");
        
       taxtext.setText(null);
       subtext.setText(null);
       totaltext.setText(null);
       

       grilltext.setEnabled(false);
       cheesetext.setEnabled(false);
       vegetext.setEnabled(false);
       coketext.setEnabled(false);
       lassitext.setEnabled(false);
       limbutext.setEnabled(false);
       
       
      grillcheck.setSelected(false);
      cheesecheck.setSelected(false);
      vegecheck.setSelected(false);
      cokecheck.setSelected(false);
      lassicheck.setSelected(false);
      limbucheck.setSelected(false);
      
      
      
    
    }                                        

    private void grilltextKeyTyped(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
        char number = evt.getKeyChar();         //this is used to take the unicode character
        
        //it determines whether the character entered is a digit
     if(!  (Character.isDigit(number))
             || (number == KeyEvent.VK_BACKSPACE) 
             || (number == KeyEvent.VK_DELETE)){
             
             evt.consume();
         
     }
    }                                  

    private void cheesetextKeyTyped(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:
                char number = evt.getKeyChar();         //this is used to take the unicode character
        
        //it determines whether the character entered is a digit
     if(!  (Character.isDigit(number))
             || (number == KeyEvent.VK_BACKSPACE) 
             || (number == KeyEvent.VK_DELETE)){
             
             evt.consume();
     }
    }                                   

    private void vegetextKeyTyped(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
                char number = evt.getKeyChar();         //this is used to take the unicode character
        
        //it determines whether the character entered is a digit
     if(!  (Character.isDigit(number))
             || (number == KeyEvent.VK_BACKSPACE) 
             || (number == KeyEvent.VK_DELETE)){
             
             evt.consume();
         
     }
               
    }                                 

    private void coketextKeyTyped(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
                char number = evt.getKeyChar();         //this is used to take the unicode character
        
        //it determines whether the character entered is a digit
     if(!  (Character.isDigit(number))
             || (number == KeyEvent.VK_BACKSPACE) 
             || (number == KeyEvent.VK_DELETE)){
             
             evt.consume();
         
     }
    }                                 

    private void lassitextKeyTyped(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
                char number = evt.getKeyChar();         //this is used to take the unicode character
        
        //it determines whether the character entered is a digit
     if(!  (Character.isDigit(number))
             || (number == KeyEvent.VK_BACKSPACE) 
             || (number == KeyEvent.VK_DELETE)){
             
             evt.consume();
         
     }
    }                                  

    private void limbutextKeyTyped(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
                char number = evt.getKeyChar();         //this is used to take the unicode character
        
        //it determines whether the character entered is a digit
     if(!  (Character.isDigit(number))
             || (number == KeyEvent.VK_BACKSPACE) 
             || (number == KeyEvent.VK_DELETE)){
             
             evt.consume();
         
     }
    }                                  

    private void grillcheckActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        if  (grillcheck.isSelected())
        {
                    grilltext.setEnabled(true);
                    grilltext.requestFocus();
                    grilltext.setText(" ");
            }
        else
        {
                    grilltext.setEnabled(false);
                    grilltext.setText("0");
        }
    }                                          

    private void cheesecheckActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
          if  (cheesecheck.isSelected())
        {
                    cheesetext.setEnabled(true);
                    cheesetext.requestFocus();
                    cheesetext.setText("");
                    
            }
        else
        {
                    cheesetext.setEnabled(false);
                    cheesetext.setText("0");
        }
    }                                           

    private void vegecheckActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
          if  (vegecheck.isSelected())
        {
                    vegetext.setEnabled(true);
                    vegetext.requestFocus();
                    vegetext.setText("");
            }
        else
        {
                    vegetext.setEnabled(false);
                    vegetext.setText("0");
        }
    }                                         

    private void cokecheckActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
          if  (cokecheck.isSelected())
        {
                    coketext.setEnabled(true);
                    coketext.requestFocus();
                    coketext.setText("");
            }
        else
        {
                    coketext.setEnabled(false);
                    coketext.setText("0");
        }
    }                                         

    private void lassicheckActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
          if  (lassicheck.isSelected())
        {
                    lassitext.setEnabled(true);
                    lassitext.requestFocus();
                    lassitext.setText("");
            }
        else
        {
                    lassitext.setEnabled(false);
                    lassitext.setText("0");
        }
    }                                          

    private void limbucheckActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
          if  (limbucheck.isSelected())
        {
                    limbutext.setEnabled(true);
                    limbutext.requestFocus();
                    limbutext.setText("");
            }
        else
        {
                    limbutext.setEnabled(false);
                    limbutext.setText("0");
        }
    }                                          

    private void grilltextActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void totalbutActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
//        itemcost[0] = Double.parseDouble(grilltext.getText());
//        itemcost[1] = Double.parseDouble(cheesetext.getText());
//        itemcost[2] = Double.parseDouble(vegetext.getText());
//        itemcost[3] = Double.parseDouble(coketext.getText());
//        itemcost[4] = Double.parseDouble(lassitext.getText());
//        itemcost[5] = Double.parseDouble(limbutext.getText());
//        

        double item0 = Double.parseDouble(grilltext.getText());
          double am0 = item0 * price_grill;
          
          double item1 = Double.parseDouble(cheesetext.getText());
          double am1 = item1 * price_cheese ;

          double item2 = Double.parseDouble(vegetext.getText());
          double am2 = item2 * price_vege ;

             double item3 = Double.parseDouble(coketext.getText());
          double am3 = item3 * price_coke ;

             double item4 = Double.parseDouble(lassitext.getText());
          double am4 = item4 * price_lassi ;

             double item5 = Double.parseDouble(limbutext.getText());
          double am5 = item5 * price_limbu ;

       itemcost[0] = am0;
       itemcost[1] = am1;
       itemcost[2] = am2;
       itemcost[3] = am3;
       itemcost[4] = am4;
       itemcost[5] = am5;
       
       String Payment = (String)jComboBox1.getSelectedItem();
       
       if( Payment == "Cash" || Payment == "Debit Card" || Payment == "Visa Card" || Payment == "Master Card")
       {
        
   Subtotal= itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] + itemcost[4] + itemcost[5];         


tax = (Subtotal * Tax_Rate)/100;

String tTax = String.format("₹%.2f",tax);
taxtext.setText(tTax);

String sub = String.format("₹%.2f",Subtotal);
subtext.setText(sub);

String ttotal  = String.format("₹%.2f", Subtotal + tax);
totaltext.setText(ttotal);
       }


    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fastfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fastfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fastfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fastfood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fastfood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox cheesecheck;
    private javax.swing.JTextField cheesetext;
    private javax.swing.JCheckBox cokecheck;
    private javax.swing.JTextField coketext;
    private javax.swing.JButton exitbut;
    private javax.swing.JCheckBox grillcheck;
    private javax.swing.JTextField grilltext;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JCheckBox lassicheck;
    private javax.swing.JTextField lassitext;
    private javax.swing.JCheckBox limbucheck;
    private javax.swing.JTextField limbutext;
    private javax.swing.JButton resetbut;
    private javax.swing.JTextField subtext;
    private javax.swing.JTextField taxtext;
    private javax.swing.JButton totalbut;
    private javax.swing.JTextField totaltext;
    private javax.swing.JCheckBox vegecheck;
    private javax.swing.JTextField vegetext;
    // End of variables declaration                   
}
